export const MOCK_CATALOGS = {
  canales: [
    { id: "1", name: "WhatsApp" },
    { id: "2", name: "Correo electrónico" },
    { id: "3", name: "Llamada Telefónica" },
    { id: "4", name: "Web" },
  ],
  tiposIntencion: [
    { id: "1", name: "Donación" },
    { id: "2", name: "Solicitud" },
  ],
  unidades: [
    { id: "1", name: "Kilos" },
    { id: "2", name: "Unidades" },
    { id: "3", name: "Litros" },
  ],
  tiposProducto: [
    { id: "1", name: "Perecible" },
    { id: "2", name: "No perecible" },
  ],
  procedencias: [
    { id: "1", name: "Nacional" },
    { id: "2", name: "Importado" },
  ],
  tipoLugar: [
    { id: "1", name: "Centro de acopio" },
    { id: "2", name: "Almacén" },
    { id: "3", name: "Planta de producción" },
  ],
  tipoAcceso: [
    { id: "1", name: "Peatonal" },
    { id: "2", name: "Vehicular" },
    { id: "3", name: "Restringido" },
  ],
  anticipacion: [
    { id: "1", name: "24 horas" },
    { id: "2", name: "48 horas" },
    { id: "3", name: "1 semana" },
  ],
  motivosDonacion: [
    { id: "1", name: "Exceso de Producción" },
    { id: "2", name: "Vencimiento Próximo" },
    { id: "3", name: "Sobrantes de Inventario" },
  ],
  compromisosIdoneidad: [
    { id: "1", name: "Garantizo Calidad" },
    { id: "2", name: "Sigo Normas Sanitarias" },
  ],
  condicionAlmacenamiento: [
    { id: "1", name: "Temperatura Ambiente" },
    { id: "2", name: "Refrigerado (0-5°C)" },
    { id: "3", name: "Congelado (-18°C)" },
  ],
  condicionesProducto: [
    { id: "1", name: "Excelente" },
    { id: "2", name: "Bueno" },
    { id: "3", name: "Regular" },
  ],
};

export const MOCK_UBIGEO = {
  departments: [
    { code: "15", name: "Lima" },
    { code: "01", name: "Amazonas" },
  ],
  provinces: {
    "15": [
      { code: "1501", name: "Lima" },
    ],
    "01": [
      { code: "0101", name: "Chachapoyas" },
    ],
  },
  districts: {
    "1501": [
      { code: "150101", name: "Lima" },
      { code: "150102", name: "Miraflores" },
      { code: "150103", name: "San Isidro" },
    ],
    "0101": [
      { code: "010101", name: "Chachapoyas" },
    ],
  },
};

export const MOCK_ORGANIZACIONES = [
  {
    Id: 1,
    Nombre: "Comedor Popular A",
    Direccion: "Av. Lima 123",
    Ubigeo: "150101",
    Categoria: "Comedor",
    Zona: "Centro",
    CapacidadSemanalKg: 500,
    KgPorPersona: 1.5,
    Beneficiarios: 300,
    HistorialCumplimiento: 0.95,
    ProductosRecibidos: ["Alimentos", "Higiene"]
  },
  {
    Id: 2,
    Nombre: "Banco de Alimentos B",
    Direccion: "Calle Sol 456",
    Ubigeo: "150102",
    Categoria: "Banco Alimentos",
    Zona: "Norte",
    CapacidadSemanalKg: 2000,
    KgPorPersona: 2.0,
    Beneficiarios: 1000,
    HistorialCumplimiento: 0.88,
    ProductosRecibidos: ["Alimentos", "Ropa"]
  },
  {
    Id: 3,
    Nombre: "Asociación Social C",
    Direccion: "Jr. Junin 789",
    Ubigeo: "150301",
    Categoria: "Asociación",
    Zona: "Sur",
    CapacidadSemanalKg: 200,
    KgPorPersona: 1.2,
    Beneficiarios: 150,
    HistorialCumplimiento: 0.92,
    ProductosRecibidos: ["Higiene", "Ropa"]
  },
];

export const INITIAL_INTENCIONES = [
  {
    id: "test-perfect",
    codigo: "INT-TEST-PERFECT",
    donante: "Donante Corporativo Test",
    contacto: "Admin Test",
    fechaIntencion: "2026-09-18",
    canal: "Web",
    responsable: "Luis",
    estado: "Capturada",
    tipoIntencion: "Donación",
    productos: [
      {
        id: "p-perfect",
        producto: "Producto Premium Test",
        descripcion: "Lote de prueba completo",
        cantidad: 100,
        unidad: "Kilos",
        pesoEstimadoKg: 100,
        vidaUtil: "2027-01-01",
        tipoProducto: "No perecible",
        procedencia: "Nacional",
        tipoLugar: "Centro de acopio",
        lugar: "Almacén Central Test",
        contactoPlanta: "Supervisor Test",
        direccion: "Av. Prueba 123",
        referencia: "Al lado del Centro Cívico",
        distrito: "150101",
        provincia: "1501",
        departamento: "15",
        codigoPostal: "15001",
        tipoAcceso: "Vehicular",
        horarioInicio: "08:00",
        horarioFinal: "17:00",
        diasAtencion: ["Lunes", "Martes", "Miércoles", "Jueves", "Viernes"],
        requiereAutorizacion: "Si",
        anticipacion: "24 horas",
        contactoAutorizacion: "Gerente de Planta",
        numeroContacto: "900000000",
        requisitosIngreso: ["DNI vigente", "SCTR"],
        fechaDesde: "2026-09-20",
        fechaHasta: "2026-09-25",
        horarioDisponible: "09:00-12:00",
        tiempoEstimadoCarga: "60",
        latitud: "-12.046374",
        longitud: "-77.042793",
        observacionesAcceso: "Ingreso por puerta 4",
      }
    ],
    documentos: [
      { id: "doc-test", nombre: "Certificado_Calidad.pdf", url: "https://via.placeholder.com/doc-test" }
    ],
    fotos: [
      { id: "img-test", nombre: "foto_producto.jpg", url: "https://via.placeholder.com/img-test" }
    ],
    createdAt: new Date().toISOString(),
    condicionProducto: "Excelente",
    condicionAlmacenamiento: "Temperatura Ambiente",
    motivoDonacion: "Exceso de Producción",
    compromisoIdoneidad: "Garantizo Calidad",
    declaracionProducto: true
  },
  {
    id: "test-coordinacion",
    codigo: "INT-COORD-TEST",
    donante: "Alimentos del Sur",
    contacto: "Ricardo Coordinador",
    fechaIntencion: "2026-09-10",
    canal: "Web",
    responsable: "Ana",
    estado: "Asignada",
    tipoIntencion: "Donación",
    productos: [
      {
        id: "p-coord",
        producto: "Granos Mixtos",
        descripcion: "Sacos de legumbres",
        cantidad: 50,
        unidad: "Sacos",
        pesoEstimadoKg: 500,
        vidaUtil: "2027-06-01",
        tipoProducto: "No perecible",
        procedencia: "Nacional",
        tipoLugar: "Centro de acopio",
        lugar: "Almacén Sur",
        contactoPlanta: "Mario Log",
        direccion: "Av. Industrial 789",
        referencia: "Cerca al puente",
        distrito: "150102",
        provincia: "1501",
        departamento: "15",
        codigoPostal: "15002",
        tipoAcceso: "Vehicular",
        horarioInicio: "08:00",
        horarioFinal: "16:00",
        diasAtencion: ["Lunes", "Martes", "Miércoles", "Jueves", "Viernes"],
        requiereAutorizacion: "No",
        anticipacion: "24 horas",
        contactoAutorizacion: "",
        numeroContacto: "944444444",
        requisitosIngreso: [],
        fechaDesde: "2026-09-15",
        fechaHasta: "2026-09-18",
        horarioDisponible: "08:00-11:00",
        tiempoEstimadoCarga: "40",
        latitud: "-12.060000",
        longitud: "-77.060000",
        observacionesAcceso: "Carga rápida",
      }
    ],
    documentos: [
      { id: "doc-coord", nombre: "Guia_Provisional.pdf", url: "https://via.placeholder.com/doc-coord" }
    ],
    fotos: [
      { id: "img-coord", nombre: "estiba.jpg", url: "https://via.placeholder.com/img-coord" }
    ],
    createdAt: new Date().toISOString(),
    condicionProducto: "Excelente",
    condicionAlmacenamiento: "Temperatura ambiente",
    motivoDonacion: "Sobrantes de Inventario",
    compromisoIdoneidad: "Empaque y etiquetado en buen estado",
    declaracionProducto: true
  },
  {
    id: "test-cierre",
    codigo: "INT-CIERRE-TEST",
    donante: "Corporación Nutrición",
    contacto: "Elena Cierre",
    fechaIntencion: "2026-09-01",
    canal: "Web",
    responsable: "Pedro",
    estado: "Cerrada",
    tipoIntencion: "Donación",
    productos: [
      {
        id: "p-cierre",
        producto: "Lácteos Variados",
        descripcion: "Cajas de leche y queso",
        cantidad: 100,
        unidad: "Cajas",
        pesoEstimadoKg: 300,
        vidaUtil: "2026-11-01",
        tipoProducto: "Perecible",
        procedencia: "Nacional",
        tipoLugar: "Planta de produccion",
        lugar: "Planta Lácteos Centro",
        contactoPlanta: "Sonia Planta",
        direccion: "Calle Lácteos 123",
        referencia: "Frente al mercado",
        distrito: "150101",
        provincia: "1501",
        departamento: "15",
        codigoPostal: "15001",
        tipoAcceso: "Vehicular",
        horarioInicio: "07:00",
        horarioFinal: "15:00",
        diasAtencion: ["Lunes", "Martes", "Miércoles", "Jueves", "Viernes"],
        requiereAutorizacion: "Si",
        anticipacion: "48 horas",
        contactoAutorizacion: "Admin Planta",
        numeroContacto: "955555555",
        requisitosIngreso: ["DNI", "Casco"],
        fechaDesde: "2026-09-05",
        fechaHasta: "2026-09-07",
        horarioDisponible: "07:00-10:00",
        tiempoEstimadoCarga: "90",
        latitud: "-12.080000",
        longitud: "-77.080000",
        observacionesAcceso: "Requiere cadena de frío",
      }
    ],
    documentos: [
      { id: "doc-cierre", nombre: "Acta_Final.pdf", url: "https://via.placeholder.com/doc-cierre" }
    ],
    fotos: [
      { id: "img-cierre", nombre: "entrega_final.jpg", url: "https://via.placeholder.com/img-cierre" }
    ],
    createdAt: new Date().toISOString(),
    condicionProducto: "Excelente",
    condicionAlmacenamiento: "Refrigerado (0-8°C)",
    motivoDonacion: "Campana solidaria",
    compromisoIdoneidad: "Cumple normativas sanitarias vigentes",
    declaracionProducto: true
  },
  {
    id: "test-calidad",
    codigo: "INT-CALIDAD-TEST",
    donante: "Donante Calidad",
    contacto: "Carlos Calidad",
    fechaIntencion: "2026-09-18",
    canal: "Web",
    responsable: "Ana",
    estado: "Capturada",
    tipoIntencion: "Donación",
    productos: [
      {
        id: "p-calidad",
        producto: "Fruta Variada",
        descripcion: "Cajas de manzana y pera",
        cantidad: 50,
        unidad: "Cajas",
        pesoEstimadoKg: 250,
        vidaUtil: "2026-10-01",
        tipoProducto: "Fruta/Verdura",
        procedencia: "Nacional",
        tipoLugar: "Planta de produccion",
        lugar: "Huerto Test",
        contactoPlanta: "Pedro Frutas",
        direccion: "Km 15 Panamericana Sur",
        referencia: "Puerta principal",
        distrito: "150101",
        provincia: "1501",
        departamento: "15",
        codigoPostal: "15001",
        tipoAcceso: "Vehicular",
        horarioInicio: "06:00",
        horarioFinal: "12:00",
        diasAtencion: ["Lunes", "Martes", "Miércoles", "Jueves", "Viernes", "Sábado"],
        requiereAutorizacion: "No",
        anticipacion: "24 horas",
        contactoAutorizacion: "",
        numeroContacto: "911111111",
        requisitosIngreso: [],
        fechaDesde: "2026-09-19",
        fechaHasta: "2026-09-21",
        horarioDisponible: "06:00-09:00",
        tiempoEstimadoCarga: "30",
        latitud: "-12.100000",
        longitud: "-77.100000",
        observacionesAcceso: "Cuidado con la humedad",
      }
    ],
    documentos: [
      { id: "doc-calidad", nombre: "Ficha_Tecnica.pdf", url: "https://via.placeholder.com/doc-calidad" }
    ],
    fotos: [
      { id: "img-calidad", nombre: "producto_calidad.jpg", url: "https://via.placeholder.com/img-calidad" }
    ],
    createdAt: new Date().toISOString(),
    condicionProducto: "Excelente",
    condicionAlmacenamiento: "Refrigerado (0-8°C)",
    motivoDonacion: "Excedente de produccion",
    compromisoIdoneidad: "Producto apto para consumo humano",
    declaracionProducto: true
  },
  {
    id: "test-logistica",
    codigo: "INT-LOGISTICA-TEST",
    donante: "Logistica Express",
    contacto: "Marta Log",
    fechaIntencion: "2026-09-18",
    canal: "Correo electronico",
    responsable: "Jorge",
    estado: "AprobadaCalidad",
    tipoIntencion: "Donación",
    productos: [
      {
        id: "p-log",
        producto: "Conservas",
        descripcion: "Latas de atún",
        cantidad: 200,
        unidad: "Unidades",
        pesoEstimadoKg: 80,
        vidaUtil: "2027-12-01",
        tipoProducto: "No perecible",
        procedencia: "Nacional",
        tipoLugar: "Centro de acopio",
        lugar: "Almacén Norte",
        contactoPlanta: "Luis Almacén",
        direccion: "Av. Industrial 456",
        referencia: "Al lado de la estación",
        distrito: "150102",
        provincia: "1501",
        departamento: "15",
        codigoPostal: "15002",
        tipoAcceso: "Vehicular",
        horarioInicio: "08:00",
        horarioFinal: "16:00",
        diasAtencion: ["Lunes", "Martes", "Miércoles", "Jueves", "Viernes"],
        requiereAutorizacion: "Si",
        anticipacion: "48 horas",
        contactoAutorizacion: "Jefe Logística",
        numeroContacto: "922222222",
        requisitosIngreso: ["DNI", "Casco", "Botas"],
        fechaDesde: "2026-09-21",
        fechaHasta: "2026-09-23",
        horarioDisponible: "10:00-14:00",
        tiempoEstimadoCarga: "45",
        latitud: "-12.050000",
        longitud: "-77.050000",
        observacionesAcceso: "Carga mediante montacargas",
      }
    ],
    documentos: [
      { id: "doc-log", nombre: "Guia_Remision.pdf", url: "https://via.placeholder.com/doc-log" }
    ],
    fotos: [
      { id: "img-log", nombre: "almacen_log.jpg", url: "https://via.placeholder.com/img-log" }
    ],
    createdAt: new Date().toISOString(),
    condicionProducto: "Excelente",
    condicionAlmacenamiento: "Temperatura ambiente",
    motivoDonacion: "Sobrantes de Inventario",
    compromisoIdoneidad: "Empaque y etiquetado en buen estado",
    declaracionProducto: true
  },
  {
    id: "test-asignacion",
    codigo: "INT-ASIGNACION-TEST",
    donante: "Asignacion Global",
    contacto: "Sofia Asig",
    fechaIntencion: "2026-09-18",
    canal: "Web",
    responsable: "Ana",
    estado: "AprobadaLogistica",
    tipoIntencion: "Donación",
    productos: [
      {
        id: "p-asig",
        producto: "Leche en Polvo",
        descripcion: "Sacos de 25kg",
        cantidad: 10,
        unidad: "Saco",
        pesoEstimadoKg: 250,
        vidaUtil: "2027-03-01",
        tipoProducto: "No perecible",
        procedencia: "Importado",
        tipoLugar: "Centro de acopio",
        lugar: "Puerto Callao",
        contactoPlanta: "Admin Puerto",
        direccion: "Av. Apurímac s/n",
        referencia: "Zona de contenedores",
        distrito: "Callao",
        provincia: "Callao",
        departamento: "Callao",
        codigoPostal: "07001",
        tipoAcceso: "Vehicular",
        horarioInicio: "07:00",
        horarioFinal: "15:00",
        diasAtencion: ["Lunes", "Martes", "Miércoles", "Jueves", "Viernes"],
        requiereAutorizacion: "Si",
        anticipacion: "72 horas",
        contactoAutorizacion: "Superintendencia",
        numeroContacto: "933333333",
        requisitosIngreso: ["Pase de puerto", "DNI"],
        fechaDesde: "2026-09-22",
        fechaHasta: "2026-09-24",
        horarioDisponible: "08:00-11:00",
        tiempoEstimadoCarga: "120",
        latitud: "-12.050000",
        longitud: "-77.150000",
        observacionesAcceso: "Control estricto de seguridad",
      }
    ],
    documentos: [
      { id: "doc-asig", nombre: "Certificado_Importacion.pdf", url: "https://via.placeholder.com/doc-asig" }
    ],
    fotos: [
      { id: "img-asig", nombre: "contenedor.jpg", url: "https://via.placeholder.com/img-asig" }
    ],
    createdAt: new Date().toISOString(),
    condicionProducto: "Excelente",
    condicionAlmacenamiento: "Lugar fresco y seco",
    motivoDonacion: "Aliado estrategico",
    compromisoIdoneidad: "Cumple normativas sanitarias vigentes",
    declaracionProducto: true
  },
  {
    id: "1",
    codigo: "INT-2026-0001",
    donante: "Donante Ejemplo",
    contacto: "Contacto Ejemplo",
    fechaIntencion: "2026-09-01",
    canal: "Web",
    responsable: "Admin",
    estado: "Capturada",
    tipoIntencion: "Donación",
    productos: [],
    documentos: [],
    fotos: [],
    createdAt: new Date().toISOString()
  }
];
